language: node_js
node_js:
  - "0.10.25"
cache:
  directories:
    - node_modules
services: mongodb
script: npm run coverage
addons:
  code_climate:
    repo_token: process.env.REPO_TOKEN
after_script:
  - codeclimate-test-reporter < lcov.info
